export const SVG_TYPES = {
  CIRCLE: 'CIRCLE',
  DEAD_SEA: 'DEAD_SEA',
  GLOBE: 'GLOBE_POOL',
  RECTANGLE: 'RECTANGLE_POOL',
  SQUARE_BIG: 'SQUARE_BIG_POOL',
  SQUARE_SMALL: 'SQUARE_SMALL_POOL',
  AMERICA: 'AMERICA_POOL',
};
